# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-08 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Society Name')),
                ('contract_number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='contact number')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('address', models.CharField(max_length=255, verbose_name='Society Location')),
                ('city', models.CharField(default='Pune', max_length=20, verbose_name='city')),
                ('state', models.CharField(default='maharashtra', max_length=20, verbose_name='state')),
                ('pin_code', models.CharField(default='411021', max_length=6, verbose_name='pin code')),
                ('lat', models.DecimalField(decimal_places=6, default=18.557024, max_digits=9, verbose_name='latitude')),
                ('long', models.DecimalField(decimal_places=6, default=73.75092, max_digits=9, verbose_name='longitude')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Society',
                'verbose_name_plural': 'Societies',
            },
        ),
    ]
