# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180710_0431'),
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Chairman', 'Chairman'), ('secretary', 'secretary'), ('treasurer', 'treasurer')], default='Chairman', max_length=9)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_member', to='accounts.Member', unique=True, verbose_name='Committee Member')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_committee', to='society.Society', verbose_name='Society')),
            ],
        ),
    ]
