# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_societycommittee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societycommittee',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee_member', to='accounts.Member', verbose_name='Committee Member'),
        ),
    ]
