# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='type',
        ),
        migrations.DeleteModel(
            name='MemberType',
        ),
    ]
