# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-08 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Visitor Name')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Phone number')),
                ('number_of_visitor', models.CharField(max_length=2, verbose_name='No. Of Visitor')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('address', models.CharField(max_length=255, verbose_name='Visitor address')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('check_in', models.DateTimeField(auto_now_add=True, verbose_name='Check In Time')),
                ('check_out', models.DateTimeField(verbose_name='Check out Time')),
                ('flat_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_flat', to='accounts.FlatDetail', verbose_name='flat_number')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_society', to='society.Society', verbose_name='society')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
            },
        ),
    ]
